project:
  type: book
  output-dir: docs
book: 
  title: "Introduction to R and RStudio"
  author: "William M. Murrah, III"
  chapters: 
    - intro.qmd
    - installR.qmd
    - tourr.qmd
    - raspl.qmd
    - directories.qmd
    - references.qmd

bibliography: book.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt